accounts/urls.py
from django.urls import path
from . import views
# from blog.feeds import LatestEntriesFeed
from django.contrib.auth import views as auth_views

app_name = 'accounts'

urlpatterns = [
    # Login
    path('light/login/', views.login_view, name='login_light'),
    path('dark/login/', views.login_view, name='login_dark'),

    # Logout
    path('light/logout/', views.logout_view, name='logout_light'),
    path('dark/logout/', views.logout_view, name='logout_dark'),

    # Register
    path('light/signup/', views.register_view, name='signup_light'),
    path('dark/signup/', views.register_view, name='signup_dark'),
    
    # Password change
    path('light/change_password/', views.change_password_view, name='change_password_light'),
    path('dark/change_password/', views.change_password_view, name='change_password_dark'),

    path('password_reset/', auth_views.PasswordResetView.as_view(template_name='accounts/password_reset.html'), name='password_reset_light'),
    path('password_reset/', auth_views.PasswordResetView.as_view(template_name='accounts/password_reset.html'), name='password_reset'),
    path('password_reset_done/', auth_views.PasswordResetDoneView.as_view(template_name='accounts/password_reset_done.html'), name='password_reset_done'),
    path('password_reset_confirm/<uidb64>/<token>/', auth_views.PasswordResetConfirmView.as_view(template_name='accounts/password_reset_confirm.html'), name='password_reset_confirm'),
    path('password_reset_complete/', auth_views.PasswordResetCompleteView.as_view(template_name='accounts/password_reset_complete.html'), name='password_reset_complete'),

    # path('password_reset/', auth_views.PasswordResetView.as_view(template_name='password_reset_form.html'), name='password_reset'),
    # path('password_reset_done/', auth_views.PasswordResetDoneView.as_view(template_name='password_reset_done.html'), name='password_reset_done'),
    # path('password_reset_confirm/uidb64/token/',auth_views.PasswordResetConfirmView.as_view(template_name='password_reset_confirm.html'), name='password_reset_confirm'),
    # path('password_reset_complete/', auth_views.PasswordResetCompleteView.as_view(template_name='password_reset_complete.html'), name='password_reset_complete'),
]
    

beyhagh_bastan/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static
from django.contrib.sitemaps.views import sitemap
from light_mode.sitemaps import StaticViewSitemap
from blog.sitemaps import BlogSitemap_single_post, BlogSitemap_category, BlogSitemap_tag
from portfolio.sitemaps import PortfolioSitemap_portfolio, PortfolioSitemap_category, PortfolioSitemap_tag

sitemaps = {
    # It seems that the app name is not important.
    "static": StaticViewSitemap,
    
    # Blog
    "blog_single_post": BlogSitemap_single_post,
    "blog_category": BlogSitemap_category,
    "blog_tag": BlogSitemap_tag,
    
    # Portfolio
    "portfolio_portfolio": PortfolioSitemap_portfolio,
    "portfolio_category": PortfolioSitemap_category,
    "portfolio_tag": PortfolioSitemap_tag,
}

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('main.urls')),
    path('', include('light_mode.urls')),
    path('blog/', include('blog.urls')),
    path('captcha/', include('captcha.urls')),
    path('summernote/', include('django_summernote.urls')),
    path('accounts/', include('accounts.urls')),
    path('portfolio/', include('portfolio.urls')),
    path(
    "sitemap.xml",
    sitemap,
    {"sitemaps": sitemaps},
    name="django.contrib.sitemaps.views.sitemap",),
    path('robots.txt', include('robots.urls')),
]
urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

blog/urls.py
from django.urls import path
from . import views
from blog.feeds import LatestEntriesFeed


app_name = 'blog'

urlpatterns = [
    path('light/', views.index_view, name='index_light'),
    path('dark/', views.index_view, name='index_dark'),
    path('light/blog-<int:pid>/', views.blog_single_view, name='blog_single_light'),
    path('dark/blog-<int:pid>/', views.blog_single_view, name='blog_single_dark'),
    path('dark/category-<str:cat_name>', views.index_view, name='category_dark'),
    path('light/category-<str:cat_name>', views.index_view, name='category_light'),
    path('dark/tag-<str:tag_name>', views.index_view, name='tag_dark'),
    path('light/tag-<str:tag_name>', views.index_view, name='tag_light'),
    path('light/search/', views.index_view, name='search_light'),
    path('dark/search/', views.index_view, name='search_dark'),
    path("light/rss/feed/", LatestEntriesFeed()),
    # path('light/search/', views.index_view, name='search_light'),
]

accounts/models.py
from django.db import models

# Create your models here.

accounts/views.py
from django.shortcuts import render, redirect, HttpResponseRedirect, HttpResponse
from django.contrib.auth import authenticate, login, logout
from django.urls import reverse
from django.contrib import messages
from django.contrib.auth.forms import AuthenticationForm, UserCreationForm
from django.contrib.auth.decorators import login_required
from django.contrib.auth.models import User

# ******************************** Change password ********************************
from django.contrib.auth import update_session_auth_hash
from django.contrib.auth.forms import PasswordChangeForm
# ******************************** Change password ********************************

def dark_light_switch(request):
    if 'dark' in request.path:
        return ('dark')
    return ('light')

def next_reload(request):
    # ************************************* This used for next value in login pages *****************************************
    next = ''
    try:
        next = (request.get_full_path()).split("next=")[1]
        return(next)
    except:
        if request.POST.get("next_reload") is not None:
            next = request.POST.get("next_reload")
            return(next)
        else:
            if request.GET.get("next") is not None:
                next = request.POST.get("next")
                return(next)
            return(next)
    # ************************************* This used for next value in login pages *****************************************

def login_view(request):
    next = next_reload(request)       # Save next
    if not request.user.is_authenticated:
        if request.method == 'POST':
            msg=""
            # ********************************************************* Checking that login is done with email or username and handle it *********************************************************
            username = request.POST.get('username')
            password = request.POST.get('password')
            author = User.objects.filter(email=username).first()
            if author is not None:
                request.POST._mutable = True
                request.POST['username'] = author
            form = AuthenticationForm(request=request, data=request.POST)
            # ********************************************************* Checking that login is done with email or username and handle it *********************************************************
            if form.is_valid():
                username = form.cleaned_data['username']
                password = form.cleaned_data['password']
                remember_me = request.POST.get('remember_me')
                user = authenticate(request, username=username, password=password)
                if user:
                    login(request, user)
                    
                    # *********************************** If remember_me was on, means (expiry(Based on sec)) ********************************
                    if remember_me: 
                        request.session.set_expiry(604800) # Here we extend session(a week).
                    else:
                        request.session.set_expiry(0) # The session will be expire after closeing browser
                    # *********************************** If remember_me was on, means (expiry(Based on sec)) ********************************

                    # Checking user that if is logined redirect to next page
                    if user.is_authenticated:
                        messages.add_message(request, messages.SUCCESS, 'خوش آمدید')
                        if next:
                            return redirect(next)
                        else:
                            return redirect('/')
                    # Checking user that if is logined redirect to next page

                    # Maybe this part is expired!
                    # ************************************* Redirect to before post after login else go to home page *************************************
                    # if 'next' in request.POST:
                    #     return redirect(request.POST.get('next'))
                    # else:
                    #     return render('/' + dark_light_switch(request))
                    # ************************************* Redirect to before post after login else go to home page *************************************
           
            # ******************************** Print just form.error_messages[invalid_login] element ********************************
            if form.errors:
                msg = "<p>لطفا نام کاربری و گذرواژه‌ای قابل قبول وارد کنید</p><p>توجه داشته باشید که ممکن است هر دو به کوچکی و بزرگی حروف حساس باشند</p>"
            #     for field in form.errors:
            #         print(field)
            #         for error in form.errors[field]:
            #             print(error)
            #             msg = msg + f"<p>{error}</p>"
            messages.add_message(request, messages.ERROR, msg)
            # ******************************** Print just form.error_messages[invalid_login] element ********************************
        context = {'next_reload': next}
        return render(request, 'accounts/login.html', context)
    else:
        return redirect('/' + dark_light_switch(request))
        # return redirect(f"/{request.POST.get('style_key')}")

@login_required
def logout_view(request):
    logout(request)
    if 'dark' in request.path:
        return redirect(request.GET.get('next'))
    return redirect(request.GET.get('next'))

def register_view(request):
    next = next_reload(request)       # Save next
    if not request.user.is_authenticated:
        if request.method == 'POST':
            msg=""
            users = ""
            form = UserCreationForm(request.POST)
            users = User.objects.filter(email=request.POST.get('email'))
            if form.is_valid():
                # Update values before save ****************************************************************
                obj = form.save(commit=False)
                obj.email = request.POST.get('email')
                # Update values before save ****************************************************************
                if len(users) == 0:
                    messages.add_message(request, messages.SUCCESS, '.ثبت نام شما با موفقیت انجام شد')
                    form.save()
                    return redirect('/accounts/light/login/?next=' + next)
            if form.errors:
                for field in form:
                    for error in field.errors:
                        msg = msg + f'<p>{error}</p>'
            if len(users) != 0:
                msg = msg + '<p>ایمیل وارد شده تکراری میباشد</p>'
            messages.add_message(request, messages.ERROR, msg)
        context = {'next_reload': next}
        return render(request, 'accounts/signup.html', context)
    else:
        return redirect('/' + dark_light_switch(request))

# **************************************** Some rolls for change password ****************************************
# Your password can’t be too similar to your other personal information.
# Your password must contain at least 8 characters.
# Your password can’t be a commonly used password.
# Your password can’t be entirely numeric.
# **************************************** Some rolls for change password ****************************************
@login_required   
def change_password_view(request):
    next = next_reload(request)       # Save next
    if request.method == 'POST':
        msg = ""
        form = PasswordChangeForm(request.user, request.POST)
        if form.is_valid():
            user = form.save()
            update_session_auth_hash(request, user)  # Important!
            messages.success(request, 'رمز عبور شما با موفقیت تغییر کرد')
            if next:
                return redirect(next)
            return redirect('/')
        else:
            if form.errors:
                for field in form.errors:
                    for error in form.errors[field]:
                        msg = msg + f"<p>{error}</p>"
            messages.error(request, msg)
    context = {'next_reload': next}
    return render(request, 'accounts/change_password.html', context)

templates/accounts/change_password.html
{% extends 'accounts/base.html' %}
{% load static %}
{% block extrahead %}
  <title>Change Password</title>
{% endblock extrahead %}
{% block content %}
  <!-- Login 2 start -->
  <div class="login-2 login-background">
    <div class="login-background-inner">
      <div class="cube"></div>
      <div class="cube"></div>
      <div class="cube"></div>
      <div class="cube"></div>
      <div class="cube"></div>
    </div>
    <div class="login-2-inner">
      <div class="container">
        <div class="row login-box">
          <div class="col-lg-6 align-self-center pad-0 form-info">
            <div class="form-section clearfix">
              <div class="logo-2 logo">
                <a href="{% if 'light' in request.path %}{% url 'accounts:login_light' %}{% else %}{% url 'accounts:login_dark' %}{% endif %}"><img src="{% static 'account_assets/img/logos/logo-2.png' %}" alt="logo" /></a>
              </div>
              <h3>تعویض رمز عبور</h3>
              <div class="btn-section clearfix">
                <a href="{% if 'light' in request.path %}{% url 'accounts:login_light' %}?next={{next_reload}}{% else %}{% url 'accounts:login_dark' %}?next={{next_reload}}{% endif %}" class="link-btn active btn-1 default-bg">ورود</a>
                <a href="{% if 'light' in request.path %}{% url 'accounts:signup_light' %}?next={{next_reload}}{% else %}{% url 'accounts:signup_dark' %}?next={{next_reload}}{% endif %}" class="link-btn btn-2 default-bg">ثبت نام</a>
              </div>
              <div class="clearfix"></div>
              <form action="{% if 'dark' in request.path %}{% url 'accounts:change_password_dark' %}?next={{ next_reload }}{% else %}{% url 'accounts:change_password_light' %}?next={{ next_reload }}{% endif %}" method="post">
                {% csrf_token %}
                {% if request.GET.next %}
                  <input type="hidden" name="next" value="{{ request.GET.next }}" />
                {% endif %}
                <input type="hidden" name="next_reload" value="{{ next_reload }}" />
                <input type="hidden" name="pid" value="{{ request.user.id }}" />
                <div class="form-group">
                  <input type="password" id="old_password" name="old_password" class="form-control ltr-with-rtl-pHolder" placeholder="رمز عبور فعلی" required />
                  <span toggle="#old_password" class="fa fa-fw fa-eye field-icon toggle-password eyes"></span>
                </div>
                <div class="form-group">
                  <input id="new_password1" name="new_password1" type="password" class="form-control ltr-with-rtl-pHolder" placeholder="رمز عبور جدید" required />
                  <span toggle="#new_password1" class="fa fa-fw fa-eye field-icon toggle-password eyes"></span>
                </div>
                <div class="form-group clearfix">
                  <input id="new_password2" name="new_password2" type="password" class="form-control ltr-with-rtl-pHolder" placeholder="تکرار رمز عبور جدید" required />
                  <span toggle="#new_password2" class="fa fa-fw fa-eye field-icon toggle-password eyes"></span>
                </div>
                <div class="form-group clearfix">
                  <button type="submit" class="btn btn-lg btn-info btn-theme">ثبت</button>
                </div>
              </form>
            </div>
          </div>
          <div class="col-lg-6 align-self-center pad-0 bg-img">
            <div class="info clearfix">
              <div class="box">
                <span></span>
                <span></span>
                <span></span>
                <span></span>
                <div class="content">
                  <div class="logo-2">
                    <a href="{% if 'light' in request.path %}{% url 'accounts:login_light' %}{% else %}{% url 'accounts:login_dark' %}{% endif %}"><img src="{% static 'account_assets/img/logos/logo.png' %}" alt="logo" /></a>
                  </div>
                  <h3>ثبت نام و ورود با</h3>
                  <div class="social-list">
                    <a href="#" class="facebook-bg"><i class="fa fa-facebook"></i></a>
                    <a href="#" class="twitter-bg"><i class="fa fa-twitter"></i></a>
                    <a href="#" class="google-bg"><i class="fa fa-google"></i></a>
                    <a href="#" class="linkedin-bg"><i class="fa fa-linkedin"></i></a>
                  </div>
                </div>
              </div>
            </div>
          </div>
        </div>
      </div>
    </div>
  </div>
  <!-- Login 2 end -->
{% endblock %}
{% block extrafooter %}
<script>
  var password = document.getElementById("new_password1")
  , confirm_password = document.getElementById("new_password2");
  
  function validatePassword(){
  if(password.value != confirm_password.value) {
    confirm_password.setCustomValidity("Passwords Don't Match");
  } else {
    confirm_password.setCustomValidity('');
  }
  }
  
  password.onchange = validatePassword;
  confirm_password.onkeyup = validatePassword;
</script>
<!-- validation password -->
{% endblock extrafooter %}

templates/accounts/login.html
{% extends 'accounts/base.html' %}
{% load static %}
{% block extrahead %}
  <title>Login</title>
{% endblock extrahead %}
{% block content %}
  <!-- Login 2 start -->
  <div class="login-2 login-background">
    <div class="login-background-inner">
      <div class="cube"></div>
      <div class="cube"></div>
      <div class="cube"></div>
      <div class="cube"></div>
      <div class="cube"></div>
    </div>
    <div class="login-2-inner">
      <div class="container">
        <div class="row login-box">
          <div class="col-lg-6 align-self-center pad-0 form-info">
            <div class="form-section align-self-center">
              <div class="logo-2 logo">
                <a href="/{% if 'light' in request.path %}light{% else %}dark{% endif %}"><img src="{% static 'account_assets/img/logos/logo-2.png' %}" alt="logo" /></a>
              </div>
              <h3>ورود به حساب کاربری</h3>
              <div class="btn-section clearfix">
                <a href="{% if 'light' in request.path %}{% url 'accounts:signup_light' %}?next={{next_reload}}{% else %}{% url 'accounts:signup_dark' %}?next={{next_reload}}{% endif %}" class="link-btn btn-1 default-bg">ثبت نام</a>
                <a href="{% if 'light' in request.path %}{% url 'accounts:login_light' %}?next={{next_reload}}{% else %}{% url 'accounts:login_dark' %}?next={{next_reload}}{% endif %}" class="link-btn active btn-2 active-bg">ورود</a>
              </div>
              <div class="clearfix"></div>
              <form action="{% if 'light' in request.path %}{% url 'accounts:login_light' %}?next={{next_reload}}{% else %}{% url 'accounts:login_dark' %}?next={{next_reload}}{% endif %}" method="post">
                {% csrf_token %}
                <input type="hidden" name="style_key" value="{% if 'light' in request.path %}{{request.get_full_path}}{% else %}dark{% endif %}">
                {% if request.GET.next %}
                  <input type="hidden" name="next" value="{{ request.GET.next }}" />
                {% endif %}
                <input type="hidden" name="next_reload" value="{{ next_reload }}" />
                <div class="form-group">
                  <input name="username" type="text" class="form-control ltr-with-rtl-pHolder" placeholder="ایمیل/نام کاربری" aria-label="Email Address" required/>
                </div>
                <div class="form-group clearfix">
                  <input name="password" id="password-field" type="password" class="form-control ltr-with-rtl-pHolder" autocomplete="off" placeholder="پسورد" aria-label="Password" required/>
                  <span toggle="#password-field" class="fa fa-fw fa-eye field-icon toggle-password eyes"></span>
                </div>
                <div class="form-group clearfix float-right">
                  <div class="form-check">
                    <input name="remember_me" class="form-check-input rememberme" type="checkbox" id="remember_me">
                    <label class="form-check-label" for="remember_me">
                      مرا به خاطر بسپار
                    </label>
                  </div>
                </div>
                <div class="form-group clearfix">
                  <button type="submit" class="btn btn-lg btn-info btn-theme">ورود</button>
                  <a href="{% if 'light' in request.path %}{% url 'accounts:password_reset' %}?next={{next_reload}}{% else %}{% url 'accounts:password_reset' %}?next={{next_reload}}{% endif %}" class="forgot-password float-end a-style">رمز خود را فراموش کرده اید؟</a>
                </div>
              </form>
              {% comment %} <p class="mb-0">
                حساب کاربری ندارید؟ <a href="{% if 'light' in request.path %}{% url 'accounts:signup_light' %}{% else %}{% url 'accounts:signup_dark' %}{% endif %}">ثبت نام</a>
              </p> {% endcomment %}
            </div>
          </div>
          <div class="col-lg-6 align-self-center pad-0 bg-img">
            <div class="info clearfix">
              <div class="box">
                <span></span>
                <span></span>
                <span></span>
                <span></span>
                <div class="content">
                  <div class="logo-2">
                    <a href="/{% if 'light' in request.path %}light{% else %}dark{% endif %}"><img src="{% static 'account_assets/img/logos/logo-2.png' %}" alt="logo" /></a>
                  </div>
                  <h3>ثبت نام و ورود با</h3>
                  <div class="social-list">
                    <a href="#" class="facebook-bg disabled-link"><i class="fa fa-facebook"></i></a>
                    <a href="#" class="twitter-bg disabled-link"><i class="fa fa-twitter"></i></a>
                    <a href="#" class="google-bg"><i class="fa fa-google"></i></a>
                    <a href="#" class="linkedin-bg disabled-link"><i class="fa fa-linkedin"></i></a>
                  </div>
                </div>
              </div>
            </div>
          </div>
        </div>
      </div>
    </div>
  </div>
  <!-- Login 2 end -->
{% endblock %}
{% block extrafooter %}

{% endblock extrafooter %}

templates/accounts/password_reset.html
{% extends 'accounts/base.html' %}
{% load static %}
{% block extrahead %}
  <title>Password Reset</title>
  <script src="https://ajax.googleapis.com/ajax/libs/jquery/2.1.1/jquery.min.js"></script>
{% endblock %}
{% block content %}
  <!-- Login 2 start -->
  <div class="login-2 login-background">
    <div class="login-background-inner">
      <div class="cube"></div>
      <div class="cube"></div>
      <div class="cube"></div>
      <div class="cube"></div>
      <div class="cube"></div>
    </div>
    <div class="login-2-inner">
      <div class="container">
        <div class="row login-box">
          <div class="col-lg-6 align-self-center pad-0 form-info">
            <div class="form-section clearfix">
              <h3>فراموشی رمز عبور</h3>

              <div class="clearfix"></div>
              <form method="post">
                {% csrf_token %}
                {% if request.GET.next %}
                  <input hidden type="text" id="next" name="next" value="{% if next == 'dark' %}{% url 'accounts:login_dark' %}?next={{ request.GET.next }}{% else %}{% url 'accounts:login_light' %}?next={{ request.GET.next }}{% endif %}" />
                {% endif %}
                <div class="form-group">
                  <input type="email" name="email" class="form-control ltr-with-rtl-pHolder" pattern="[A-Za-z0-9._%+-]+@[A-Za-z0-9.-]+\.[A-Za-z]{1,63}$" placeholder="ایمیل ای که با آن ثبت نام کرده اید را وارد نمائید" required />
                </div>
                <div class="form-group clearfix">
                  <button type="submit" class="form-control btn btn-info btn-theme">ارسال لینک ورود</button>
                </div>
              </form>
              <p class="mb-0">آیا قبلا ثبت نام کرده اید؟ <a id="myLink" href="" class="a-style">ورود</a></p>
            </div>
          </div>
          <div class="col-lg-6 align-self-center pad-0 bg-img">
            <div class="info clearfix">
              <div class="box">
                <span></span>
                <span></span>
                <span></span>
                <span></span>
                <div class="content">
                  <div class="logo-2">
                    <a href="/{% if 'dark' in request.path %}dark{% else %}light{% endif %}">
                      <img src="{% static 'account_assets/img/logos/logo-2.png' %}" alt="logo" />
                    </a>
                  </div>
                  <h3>ثبت نام و ورود با</h3>
                  <div class="social-list">
                    <a href="" class="facebook-bg disabled-link"><i class="fa fa-facebook"></i></a>
                    <a href="" class="twitter-bg disabled-link"><i class="fa fa-twitter"></i></a>
                    <a href="" class="google-bg"><i class="fa fa-google"></i></a>
                    <a href="" class="linkedin-bg disabled-link"><i class="fa fa-linkedin"></i></a>
                  </div>
                </div>
              </div>
            </div>
          </div>
        </div>
      </div>
    </div>
  </div>
  <!-- Login 2 end -->
{% endblock %}
{% block extrafooter %}
<script>
  {% comment %} $('#next').on('input', function() {
    var href = new URL($('#myLink').prop('href'));
    href.searchParams.set('amount', this.value);
    $('#myLink').prop('href', href.toString())
  }); {% endcomment %}
  input = document.getElementById('next');
  a = document.getElementById('myLink');
  a.setAttribute('href',input.value);
</script>
{% endblock extrafooter %}

templates/accounts/signup.html
{% extends 'accounts/base.html' %}
{% load static %}
{% block extrahead %}
  <title>Sign up</title>
{% endblock %}
{% block content %}
  <!-- Login 2 start -->
  <div class="login-2 login-background">
    <div class="login-background-inner">
      <div class="cube"></div>
      <div class="cube"></div>
      <div class="cube"></div>
      <div class="cube"></div>
      <div class="cube"></div>
    </div>
    <div class="login-2-inner">
      <div class="container">
        <div class="row login-box">
          <div class="col-lg-6 align-self-center pad-0 form-info">
            <div class="form-section clearfix">
              <div class="logo-2 logo">
                <a href="/{% if 'light' in request.path %}light{% else %}dark{% endif %}">
                  <img src="{% static 'account_assets/img/logos/logo-2.png' %}" alt="logo" />
                </a>
              </div>
              <h3>دسترسی هات رو بیشتر کن</h3>
              <div class="btn-section clearfix">
                <a href="{% if 'light' in request.path %}{% url 'accounts:signup_light' %}?next={{next_reload}}{% else %}{% url 'accounts:signup_dark' %}?next={{next_reload}}{% endif %}"class="link-btn btn-1 active-bg">ثبت نام</a>
                <a href="{% if 'light' in request.path %}{% url 'accounts:login_light' %}?next={{next_reload}}{% else %}{% url 'accounts:login_dark' %}?next={{next_reload}}{% endif %}"class="link-btn active btn-2 default-bg">ورود</a>
              </div>
              <div class="clearfix"></div>
              <form action="{% if 'light' in request.path %}{% url 'accounts:signup_light' %}?next={{next_reload}}{% else %}{% url 'accounts:signup_dark' %}?next={{next_reload}}{% endif %}"method="post">
                {% csrf_token %}
                {% if request.GET.next %}
                  <input type="hidden" name="next" value="{{ request.GET.next }}" />
                {% endif %}
                <input type="hidden" name="next_reload" value="{{ next_reload }}" />
                <div class="form-group">
                  <input type="text" name="username" class="form-control ltr-with-rtl-pHolder" placeholder="نام کاربری" autocomplete="off" required autofocus />
                </div>
                <div class="form-group">
                  <input type="email" name="email" class="form-control ltr-with-rtl-pHolder" placeholder="آدرس ایمیل" autocomplete="off" required />
                </div>
                <div class="form-group clearfix">
                  <input type="password" id="password-field" name="password1" class="form-control ltr-with-rtl-pHolder" autocomplete="off" placeholder="رمز عبور" required />
                  <span toggle="#password-field" class="fa fa-fw fa-eye field-icon toggle-password eyes"></span>
                </div>
                <div class="form-group clearfix">
                  <input type="password" id="confirm_password" name="password2" class="form-control ltr-with-rtl-pHolder" autocomplete="off" placeholder="تکرار رمز عبور" required />
                  <span toggle="#confirm_password" class="fa fa-fw fa-eye field-icon toggle-password eyes"></span>
                </div>
                <div class="form-group clearfix float-right">
                  <div class="form-check">
                    <label class="form-check-label" for="rememberme">.با ثبت نام<a href="/" class="a-style">&nbsp;شرایط و قوانین سایت&nbsp;</a>را خواهید پذیرفت</label>
                  </div>
                </div>
                <div class="form-group clearfix">
                  <button type="submit" class="btn btn-lg btn-info btn-theme">ثبت نام</button>
                </div>
              </form>
            </div>
          </div>
          <div class="col-lg-6 align-self-center pad-0 bg-img">
            <div class="info clearfix">
              <div class="box">
                <span></span>
                <span></span>
                <span></span>
                <span></span>
                <div class="content">
                  <div class="logo-2">
                    <a href="/{% if 'light' in request.path %}light{% else %}dark{% endif %}"><img src="{% static 'account_assets/img/logos/logo-2.png' %}" alt="logo" /></a>
                  </div>
                  <h3>ثبت نام و ورود با</h3>
                  <div class="social-list">
                    <a href="#" class="facebook-bg disabled-link"><i class="fa fa-facebook"></i></a>
                    <a href="#" class="twitter-bg disabled-link"><i class="fa fa-twitter"></i></a>
                    <a href="#" class="google-bg"><i class="fa fa-google"></i></a>
                    <a href="#" class="linkedin-bg disabled-link"><i class="fa fa-linkedin"></i></a>
                  </div>
                </div>
              </div>
            </div>
          </div>
        </div>
      </div>
    </div>
  </div>
  <!-- Login 2 end -->
{% endblock %}
{% block extrafooter %}

{% endblock %}