beyhagh_bastan/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static
from django.contrib.sitemaps.views import sitemap
from light_mode.sitemaps import StaticViewSitemap
from blog.sitemaps import BlogSitemap_single_post, BlogSitemap_category, BlogSitemap_tag
from portfolio.sitemaps import PortfolioSitemap_portfolio, PortfolioSitemap_category, PortfolioSitemap_tag

sitemaps = {
    # It seems that the app name is not important.
    "static": StaticViewSitemap,
    
    # Blog
    "blog_single_post": BlogSitemap_single_post,
    "blog_category": BlogSitemap_category,
    "blog_tag": BlogSitemap_tag,
    
    # Portfolio
    "portfolio_portfolio": PortfolioSitemap_portfolio,
    "portfolio_category": PortfolioSitemap_category,
    "portfolio_tag": PortfolioSitemap_tag,
}

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('main.urls')),
    path('', include('light_mode.urls')),
    path('blog/', include('blog.urls')),
    path('captcha/', include('captcha.urls')),
    path('summernote/', include('django_summernote.urls')),
    path('accounts/', include('accounts.urls')),
    path('portfolio/', include('portfolio.urls')),
    path(
    "sitemap.xml",
    sitemap,
    {"sitemaps": sitemaps},
    name="django.contrib.sitemaps.views.sitemap",),
    path('robots.txt', include('robots.urls')),
]
urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

blog/urls.py
from django.urls import path
from . import views
from blog.feeds import LatestEntriesFeed


app_name = 'blog'

urlpatterns = [
    path('light/', views.index_view, name='index_light'),
    path('dark/', views.index_view, name='index_dark'),
    path('light/blog-<int:pid>/', views.blog_single_view, name='blog_single_light'),
    path('dark/blog-<int:pid>/', views.blog_single_view, name='blog_single_dark'),
    path('dark/category-<str:cat_name>', views.index_view, name='category_dark'),
    path('light/category-<str:cat_name>', views.index_view, name='category_light'),
    path('dark/tag-<str:tag_name>', views.index_view, name='tag_dark'),
    path('light/tag-<str:tag_name>', views.index_view, name='tag_light'),
    path('light/search/', views.index_view, name='search_light'),
    path('dark/search/', views.index_view, name='search_dark'),
    path("light/rss/feed/", LatestEntriesFeed()),
    # path('light/search/', views.index_view, name='search_light'),
]

light_mode/urls.py
from django.urls import path
from . import views

app_name = 'light_mode'

# It is useable when that moved on db
# Debug is False
# from django.conf.urls import handler404
# handler404 = 'light_mode.views.custom_404'

urlpatterns = [
    # ********************************************* Home pages ****************************************
    path('light/', views.index_carousel2_view, name='index_carousel2'),
    path('dark/', views.index_carousel2_view, name='index_carousel2_dark'),
    # path('', views.index_slider_view, name='index_slider'),
    # path('', views.index_carousel_view, name='index_carousel'),
    # path('', views.index_video_view, name='index_video'),
    # path('', views.index_imagesGrid_view, name='index_imagesGrid'),
    # ********************************************* Home pages ****************************************

    path('light/404_error_page/', views.error_page_404, name='404_error_page'),

    path('light/about/', views.about_view, name='about'),
    path('dark/about/', views.about_view, name='about_dark'),
    path('light/contact/', views.contact_view, name='contact'),
    path('dark/contact/', views.contact_view, name='contact_dark'),
    path('newsletter', views.newsletter_view, name='news_letter'),
]

portfolio/urls.py
from django.urls import path
from . import views
# from blog.feeds import LatestEntriesFeed
from django.contrib.auth import views as auth_views
from portfolio.feeds import LatestEntriesFeed


app_name = 'portfolio'

urlpatterns = [
    path('light/', views.index_view, name='portfolio_light'),
    path('dark/', views.index_view, name='portfolio_dark'),
    path('light/category-<str:cat_name>', views.index_view, name='category_light'),
    path('dark/category-<str:cat_name>', views.index_view, name='category_dark'),
    path('light/tag-<str:tag_name>', views.index_view, name='tag_light'),
    path('dark/tag-<str:tag_name>', views.index_view, name='tag_dark'),
    path('search/', views.index_view, name='search'),
    path('light/single-<int:pid>', views.portfolio_single_view, name='portfolio_single_light'),
    path('dark/single-<int:pid>', views.portfolio_single_view, name='portfolio_single_dark'),
    path("light/rss/feed/", LatestEntriesFeed()),

]
    

portfolio/models.py
from django.db import models
from django.urls import reverse

# Create your models here.
class Category(models.Model):
    name = models.CharField(max_length=255)
    def __str__(self):
        return self.name
    
    def get_absolute_url(self):
        return reverse("portfolio:category_light", kwargs={"cat_name": self.name})


# I don't use taggit here because it dosent work for persian words so I create a Tag model same Category model       
class Tag(models.Model):
    name = models.CharField(max_length=255)
    def __str__(self):
        return self.name
    
    def get_absolute_url(self):
        return reverse("portfolio:tag_light", kwargs={"tag_name": self.name})

class Product(models.Model):
    # *** Attention *** for using (Char field) or (Text field) for setting empty in these it's better don't use null=True just use blank=True Because django use in two case 2values("", None)
    image_main = models.ImageField(upload_to = 'portfolio/', default='portfolio/default.jpg')
    product_id = models.CharField(max_length=255, blank=True)
    title = models.CharField(max_length=255)
    sub_title = models.CharField(max_length=255, blank=True)
    product_age = models.IntegerField(blank=True, null=True)
    dimensions = models.CharField(max_length=255, blank=True)
    material = models.CharField(max_length=255, blank=True)
    weight = models.IntegerField(blank=True, null=True)
    color = models.CharField(max_length=255, blank=True)
    price = models.FloatField(blank=True, null=True)
    info = models.TextField()
    more_info = models.TextField(blank=True)
    category = models.ManyToManyField(Category)
    tag = models.ManyToManyField(Tag)
    counted_views = models.IntegerField(default=0)
    status = models.BooleanField(default=False)
    login_require = models.BooleanField(default=False)
    published_date = models.DateTimeField()
    created_date = models.DateTimeField(auto_now_add=True)
    updated_date = models.DateTimeField(auto_now=True)

    class Meta:
        ordering = ['created_date'] # ['created_date'] reverse_order
        # How to change name of the class
        # verbose_name = 'پست'
        # verbose_name_plural = 'پست ها'

    def __str__(self):
        return self.title
    
    def get_absolute_url(self):
        return reverse('portfolio:portfolio_single_light', kwargs={'pid': self.id})
    
# Created for Posts' images excluded image-main
class ProductImage(models.Model):
    product = models.ForeignKey(Product, on_delete=models.CASCADE)
    name = models.CharField(max_length=255)
    image = models.ImageField(upload_to = 'product/')

    class Meta:
        ordering = ['product']

    def __str__(self):
        return self.image.url

class Comment(models.Model):
    product = models.ForeignKey(Product, on_delete=models.CASCADE)
    name = models.CharField(max_length=255)
    email = models.EmailField()
    subject = models.CharField(max_length=255)
    message = models.TextField()
    approved = models.BooleanField(default=False)
    created_date = models.DateTimeField(auto_now_add=True)
    published_date = models.DateTimeField(auto_now=True)

    class Meta:
        ordering = ['-created_date']

    def __str__(self):
        return self.name

portfolio/views.py
from django.shortcuts import render, redirect, get_object_or_404
from datetime import datetime
from django.utils import timezone
from django.core.paginator import Paginator, EmptyPage, PageNotAnInteger
from .models import Product, ProductImage, Comment
# from .forms import CommentForm
from django.contrib import messages
from django.db.models import Q

# def index_view(request):
#     return render(request, 'portfolio/portfolio-vertical.html')
# def single_view(request):
#     return render(request, "portfolio/portfolio-single-vertical.html")
def dark_light_switch(request):
    if 'dark' in request.path:
        return ('dark')
    return ('light')

def check_published_date():
    # Now time with timezone
    now = datetime.now()
    now = timezone.make_aware(datetime(now.year, now.month, now.day, now.hour, now.minute, now.second))
    # Now time without timezone
    # now = datetime(now.year, now.month, now.day, now.hour, now.minute, now.second)
    products = Product.objects.filter(published_date__lte=now, status=1)
    return products

def index_view(request, **kwargs):
    products = check_published_date()
    # Category validation ***********************************************************************************
    if kwargs is not None:
        if kwargs.get('cat_name') is not None:
            products = products.filter(category__name=kwargs['cat_name'])
        elif kwargs.get('author_username') is not None:
            products = products.filter(author__username=kwargs['author_username'])
        elif kwargs.get('tag_name') is not None:
            products = products.filter(tag__name=kwargs['tag_name'])
    # Category validation ***********************************************************************************
            
    # Search validations *************************************************************************************
    # if request.method == 'GET':
    #     if x:= request.GET.get('sBar'):
    #         products = products.filter(Q(content_1__contains=x) | Q(content_2__contains=x))
    # Search validations *************************************************************************************
            
    # Deleting duplicated values from tag and category ********************************************************************
    tag_con = []
    cat_con = []
    tag_id = []
    for product in products:
        for tag in product.tag.all():
            tag_con.append(str(tag))
            tag_id.append(str(tag.id))
        for cat in product.category.all():
            cat_con.append(str(cat))
    tag_con = list(dict.fromkeys(tag_con))
    cat_con = list(dict.fromkeys(cat_con))
    tag_id = list(dict.fromkeys(tag_id))
    
    zipped_tag_id = zip(tag_con, tag_id)
    
    # Deleting duplicated values from tag and category ********************************************************************

    context = {'products': products, 'tag_con': tag_con, 'cat_con': cat_con, 'zipped_tag_id': zipped_tag_id}
    return render(request, 'portfolio/portfolio-vertical.html', context)
    

def portfolio_single_view(request, pid):
    # ******************************** About CommentForm ********************************
    # if request.method == 'POST':
    #     form = CommentForm(request.POST)
    #     if form.is_valid():
    #         messages.add_message(request, messages.SUCCESS, 'دیدگاه شما با موفقیت ثبت گردید')
    #         form.save()
    #     else:
    #         messages.add_message(request, messages.ERROR, 'متاسفانه دیدگاه شما ثبت نشد')
    # form = CommentForm()
    # ******************************** About CommentForm ********************************

    products = check_published_date()
    context = get_object_or_404(products, pk=pid)
    if context.login_require == True and not request.user.is_authenticated:
        messages.add_message(request, messages.INFO, 'You are not logged in<br>Please login')
        # return redirect('accounts:login', 'blog:index')
        return redirect("/accounts/login/?next=" + request.path)
    # comments = Comment.objects.filter(post=context.id, approved = True)
    context.counted_views = context.counted_views + 1
    context.save()
    # Finding the post before and after
    nextProduct = products.filter(pk__gt=pid).first()
    prevProduct = products.filter(pk__lt=pid).last()
    images = ProductImage.objects.filter(product_id=pid)
    context = {'product': context, 'prevProduct': prevProduct, 'nextProduct': nextProduct, 'images': images}
    # context = {'context': context, 'prevProduct': prevProduct, 'nextProduct': nextProduct, 'comments': comments, 'form': form, 'images': images}
    return render(request, 'portfolio/portfolio-single-vertical.html', context)

templates/portfolio/portfolio-single-vertical.html
{% extends 'base.html' %}
{% load static %}
{% block extrahead %}

{% endblock %}
{% block content %}
  <!-- wrapper -->
  <div id="wrapper">
    <!-- content-holder -->
    <div class="content-holder" data-pagetitle="About Us">
      <!-- column-image -->
      <div class="column-image">
        <div class="bg" data-bg="{% static 'images/bg/18.jpg' %}"></div>
        <div class="overlay"></div>
        <div class="column-title">
          <h2>جزئیات بیشتر</h2>
          <h3>.برای دریافت هر گونه اطلاعات بیشتر از کالا میتوانید از شماره تلفن و ایمیل  مشخص شده در سایت استفاده نمایید</h3>
        </div>
        <div class="ci_dec">
          <span></span>
        </div>
      </div>
      <!-- column-image end -->
      <!-- column-wrapper -->
      <div class="column-wrapper">
        <section id="sec1">
          <div class="container small-container">
            <div class="section-title fl-wrap">
              <div class="section-number">.01</div></br></br>
              <h3>{{ product.title }}</h3>
              <h4>{{ product.sub_title }}</h4>
            </div>
          </div>
          <div class="container small-container">
            <!-- portfolio start -->
            <div class="gallery-items lightgallery two-column big-padding sg_items scale_anim">
              <!-- gallery-item -->
              {% for image in images %}
                <div class="gallery-item">
                {% comment %} <div class="gallery-item {% if forloop.counter == 3 or forloop.counter == 6 or forloop.counter == 9 %}{% endif %}"> {% endcomment %}
                  <div class="grid-item-holder hov_zoom">
                    <a href="{{ image }}" class="box-media-zoom popup-image"><i class="fal fa-search"></i></a>
                    <img src="{{ image }}" alt="" />
                  </div>
                </div>
              {% endfor %}
              <!-- gallery-item end -->
            </div>
            <!-- gallery-items end -->
          </div>
          <div class="container small-container">
            <div class="single_det_wrap">
              <p>{{ product.info|safe }}</p>
              <p>{{ product.more_info|safe }}</p><br /><br /><br /><br />
              <div class="caption-wrap det-anim">
                <ul>
                  <li>
                    <span class="center">(میلیمتر)ابعاد</span>
                    <a class="center">{{product.dimensions}}</a>
                  </li>
                  <li>
                    <span class="center">جنس</span>
                    <a class="center">{{product.material}}</a>
                  </li>
                  <li>
                    <span class="center">(گرم)وزن</span>
                    <a class="center">{{product.weight}}</a>
                  </li>
                  <li>
                    <span class="center">(سال)قدمت</span>
                    <a class="center">{{product.product_age}}</a>
                  </li>
                </ul><br /><br /><br />
                <ul>
                  <li>
                    <span class="center">دسته بندی</span>
                    <a class="center">{{product.category.first}}</a>
                  </li>
                  <li>
                    <span class="center">تنوع رنگ موجود</span>
                    <a class="center">{{product.color}}</a>
                  </li>
                  <li>
                    <span class="center">قیمت پایه</span>
                    <a class="center">{% if product.price == None %}--تماس بگیرید--{% else %}{{product.price}}{% endif %}</a>
                  </li>
                  <li>
                    <span class="center">دیده شده</span>
                    <a class="center">{{product.counted_views}}</a>
                  </li>
                </ul>
              </div>
              {% comment %} <a href="#" class="btn">View Case</a> {% endcomment %}
            </div>
          </div>
        </section>
        <section>
          <div class="container small-container">
            <div class="section-title n_dec st_small">
              <h3>دیدگاه ها</h3>
            </div>
            <div class="comment-item">
              <div id="disqus_thread"></div>
                <script>
                    /**
                    *  RECOMMENDED CONFIGURATION VARIABLES: EDIT AND UNCOMMENT THE SECTION BELOW TO INSERT DYNAMIC VALUES FROM YOUR PLATFORM OR CMS.
                    *  LEARN WHY DEFINING THESE VARIABLES IS IMPORTANT: https://disqus.com/admin/universalcode/#configuration-variables    */
                    /*
                    var disqus_config = function () {
                    this.page.url = PAGE_URL;  // Replace PAGE_URL with your page's canonical URL variable
                    this.page.identifier = PAGE_IDENTIFIER; // Replace PAGE_IDENTIFIER with your page's unique identifier variable
                    };
                    */
                    (function() { // DON'T EDIT BELOW THIS LINE
                    var d = document, s = d.createElement('script');
                    s.src = 'https://http-127-0-0-1-8000-nno4pazhpy.disqus.com/embed.js';
                    s.setAttribute('data-timestamp', +new Date());
                    (d.head || d.body).appendChild(s);
                    })();
                </script>
                <noscript>Please enable JavaScript to view the <a href="https://disqus.com/?ref_noscript">comments powered by Disqus.</a></noscript>
            </div>
          </div>
        </section>
        <div class="order-wrap">
          <div class="container small-container">
            <h4>آماده شرکت در گالری هستید؟</h4>
          </div>
          <a href="{% if 'dark' in request.path %}
              {% url 'light_mode:contact_dark' %}
            {% else %}
              {% url 'light_mode:contact' %}
            {% endif %}"
            class="order_btn">
            ارتباط با ما
          </a>
        </div>
      </div>
      <!-- column-wrapper -->
      <!-- fixed-bottom-container -->
      <div class="fixed-bottom-container">
        <div class="scroll-down-wrap">
          <div class="mousey">
            <div class="scroller"></div>
          </div>
        </div>
        <div class="aside_icon_wrap hbn_vis">
          <div class="list">
            <a href="{% if 'dark' in request.path %}
                {% url 'portfolio:portfolio_dark' %}
              {% else %}
                {% url 'portfolio:portfolio_light' %}
              {% endif %}">
              <span>
                <i class="b1 c1"></i><i class="b1 c2"></i><i class="b1 c3"></i>
                <i class="b2 c1"></i><i class="b2 c2"></i><i class="b2 c3"></i>
                <i class="b3 c1"></i><i class="b3 c2"></i><i class="b3 c3"></i>
              </span>
            </a>
          </div>
          <strong>برگشت به محصولات</strong>
        </div>
        <div class="progress-bar-wrap" style="height: 170px;">
          <div class="progress-bar color-bg"></div>
        </div>
      </div>
      <!-- fixed-bottom-container end -->
    </div>
    <!-- content-holder end -->
  </div>
  <!-- wrapper end -->
{% endblock %}

templates/portfolio/portfolio-vertical.html
{% extends 'base.html' %}
{% load static %}
{% block extrahead %}
{% endblock %}
{% load portfolio_tags %}
{% block content %}
  <!-- wrapper -->
  <div id="wrapper">
    <!-- content-holder -->
    <div class="content-holder">
      <!-- vertical-portfolio_wrap -->
      <div class="vertical-portfolio_wrap" id="port-scroll">
        <!-- portfolio start -->
        <div class="gallery-items big-padding lightgallery gi_left_al">
          {% for product in products %}
            <!-- gallery-item -->
            <div class="gallery-item {% for tag in product.tag.all %}{{tag.id}} {% endfor %}">
              <div class="grid-item-holder hov_zoom">
                <img src="{{ product.image_main.url }}" alt="" />
                <div class="grid-item-info">
                  <h3><a href="{% if 'dark' in request.path %}{% url 'portfolio:portfolio_single_dark' product.id %}{% else %}{% url 'portfolio:portfolio_single_light' product.id %}{% endif %}" class="ajax">{{ product.title }}</a></h3>
                  <p>{{ product.sub_title }}</p>
                </div>
                <div class="pr_num"></div>
                <a href="{{ product.image_main.url }}" class="grid-media-zoom image-popup"><i class="far fa-search"></i></a>
              </div>
            </div>
            <!-- gallery-item end -->
          {% endfor %}
        </div>
        <!-- portfolio end -->
      </div>
      <!-- vertical-portfolio_wrap end -->
      <!-- fixed-bottom-container -->
      <div class="fixed-bottom-container f_bc_vis">
        <div class="scroll-down-wrap">
          <div class="mousey">
            <div class="scroller"></div>
          </div>
        </div>
        <div class="filter-btn hid-filter">
          <div class="filter-btn_container"></div>
          <span class="filt-title">برچسب ها</span>
        </div>
        <div class="folio-counter">
          <div class="num-album"></div>
          <div class="all-album"></div>
        </div>
      </div>
      <!-- fixed-bottom-container end -->
      <!-- gallery-filters-wrap -->
      <div class="gallery-filters-wrap">
        <div class="gallery-filters">
          {% comment %} <a href="#" class="gallery-filter gallery-filter-active" data-filter="*">All Cases</a>
          <a href="#" class="gallery-filter" data-filter=".nature">Nature</a>
          <a href="#" class="gallery-filter" data-filter=".models">Models</a>
          <a href="#" class="gallery-filter" data-filter=".couples">Couples</a>
          <a href="#" class="gallery-filter" data-filter=".outdoor">Outdoor</a> {% endcomment %}
          <a href="{% if 'dark' in request.path %}{% url 'portfolio:portfolio_dark' %}{% else %}{% url 'portfolio:portfolio_light' %}{% endif %}" class="gallery-filter text_bloder">تمامی محصولات</a><br><br><br>
          {% for tag, id in zipped_tag_id %}
          <a href="#" class="gallery-filter" data-filter=".{{id}}">{{tag}}</a>

          {% comment %} It handles id_con's index {% endcomment %}
          {% comment %} <a href="{% if 'dark' in request.path %}{% url 'portfolio:category_dark' cat %}{% else %}{% url 'portfolio:category_light' cat %}{% endif %}" class="gallery-filter" data-filter=".{{cat_id}}">{{cat}}{{cat_id|value:forloop.counter0}}</a> {% endcomment %}

            {% comment %} The (modulo calculates mode of a number) {% endcomment %}
            {% if forloop.counter|modulo:5  %}<br><br>{% endif %}
          {% endfor %}
        </div>
        <div class="gallery-filters-overlay"></div>
      </div>
      <!-- gallery-filters-wrap end -->
    </div>
    <!-- content-holder end -->
  </div>
  <!-- wrapper end -->
{% endblock %}