beyhagh_bastan/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static
from django.contrib.sitemaps.views import sitemap
from light_mode.sitemaps import StaticViewSitemap
from blog.sitemaps import BlogSitemap_single_post, BlogSitemap_category, BlogSitemap_tag
from portfolio.sitemaps import PortfolioSitemap_portfolio, PortfolioSitemap_category, PortfolioSitemap_tag

sitemaps = {
    # It seems that the app name is not important.
    "static": StaticViewSitemap,
    
    # Blog
    "blog_single_post": BlogSitemap_single_post,
    "blog_category": BlogSitemap_category,
    "blog_tag": BlogSitemap_tag,
    
    # Portfolio
    "portfolio_portfolio": PortfolioSitemap_portfolio,
    "portfolio_category": PortfolioSitemap_category,
    "portfolio_tag": PortfolioSitemap_tag,
}

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('main.urls')),
    path('', include('light_mode.urls')),
    path('blog/', include('blog.urls')),
    path('captcha/', include('captcha.urls')),
    path('summernote/', include('django_summernote.urls')),
    path('accounts/', include('accounts.urls')),
    path('portfolio/', include('portfolio.urls')),
    path(
    "sitemap.xml",
    sitemap,
    {"sitemaps": sitemaps},
    name="django.contrib.sitemaps.views.sitemap",),
    path('robots.txt', include('robots.urls')),
]
urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

blog/urls.py
from django.urls import path
from . import views
from blog.feeds import LatestEntriesFeed


app_name = 'blog'

urlpatterns = [
    path('light/', views.index_view, name='index_light'),
    path('dark/', views.index_view, name='index_dark'),
    path('light/blog-<int:pid>/', views.blog_single_view, name='blog_single_light'),
    path('dark/blog-<int:pid>/', views.blog_single_view, name='blog_single_dark'),
    path('dark/category-<str:cat_name>', views.index_view, name='category_dark'),
    path('light/category-<str:cat_name>', views.index_view, name='category_light'),
    path('dark/tag-<str:tag_name>', views.index_view, name='tag_dark'),
    path('light/tag-<str:tag_name>', views.index_view, name='tag_light'),
    path('light/search/', views.index_view, name='search_light'),
    path('dark/search/', views.index_view, name='search_dark'),
    path("light/rss/feed/", LatestEntriesFeed()),
    # path('light/search/', views.index_view, name='search_light'),
]

light_mode/urls.py
from django.urls import path
from . import views

app_name = 'light_mode'

# It is useable when that moved on db
# Debug is False
# from django.conf.urls import handler404
# handler404 = 'light_mode.views.custom_404'

urlpatterns = [
    # ********************************************* Home pages ****************************************
    path('light/', views.index_carousel2_view, name='index_carousel2'),
    path('dark/', views.index_carousel2_view, name='index_carousel2_dark'),
    # path('', views.index_slider_view, name='index_slider'),
    # path('', views.index_carousel_view, name='index_carousel'),
    # path('', views.index_video_view, name='index_video'),
    # path('', views.index_imagesGrid_view, name='index_imagesGrid'),
    # ********************************************* Home pages ****************************************

    path('light/404_error_page/', views.error_page_404, name='404_error_page'),

    path('light/about/', views.about_view, name='about'),
    path('dark/about/', views.about_view, name='about_dark'),
    path('light/contact/', views.contact_view, name='contact'),
    path('dark/contact/', views.contact_view, name='contact_dark'),
    path('newsletter', views.newsletter_view, name='news_letter'),
]

blog/models.py
from django.db import models
from django.contrib.auth.models import User
from django.urls import reverse

# Create your models here.
class Category(models.Model):
    name = models.CharField(max_length=255)
    def __str__(self):
        return self.name
    def get_absolute_url(self):
        return reverse("blog:category_light", kwargs={"cat_name": self.name})

# I don't use taggit here because it dosent work for persian words so I create a Tag model same Category model       
class Tag(models.Model):
    name = models.CharField(max_length=255)
    def __str__(self):
        return self.name
    def get_absolute_url(self):
        return reverse("blog:tag_light", kwargs={"tag_name": self.name})

class Post(models.Model):
    author = models.ForeignKey(User, on_delete=models.SET_NULL, null=True)
    image_main = models.ImageField(upload_to = 'blog/', default='blog/default.jpg')
    image_content_1 = models.ImageField(upload_to = 'blog/', default='blog/image_content.png')
    image_content_2 = models.ImageField(upload_to = 'blog/', default='blog/image_content.png')
    title = models.CharField(max_length=255)
    sub_title = models.CharField(max_length=255)
    content_1 = models.TextField()
    content_2 = models.TextField()
    category = models.ManyToManyField(Category)
    tag = models.ManyToManyField(Tag)
    counted_views = models.IntegerField(default=0)
    status = models.BooleanField(default=False)
    login_require = models.BooleanField(default=False)
    published_date = models.DateTimeField()
    created_date = models.DateTimeField(auto_now_add=True)
    updated_date = models.DateTimeField(auto_now=True)

    class Meta:
        ordering = ['created_date'] # ['created_date'] reverse_order
        # How to change name of the class
        # verbose_name = 'پست'
        # verbose_name_plural = 'پست ها'

    def __str__(self):
        return self.title
    
    def get_absolute_url(self):
        return reverse('blog:blog_single_light', kwargs={'pid': self.id})   # It handles reverse items for sitemaps and create a button in the admin for each post
    
# Created for Posts' images excluded image-main
class PostImage(models.Model):
    post = models.ForeignKey(Post, on_delete=models.CASCADE)
    name = models.CharField(max_length=255)
    image = models.ImageField(upload_to = 'blog/')

    class Meta:
        ordering = ['post']

    def __str__(self):
        return self.image.url
    
class Comment(models.Model):
    post = models.ForeignKey(Post, on_delete=models.CASCADE)
    name = models.CharField(max_length=255)
    email = models.EmailField()
    subject = models.CharField(max_length=255)
    message = models.TextField()
    approved = models.BooleanField(default=False)
    created_date = models.DateTimeField(auto_now_add=True)
    published_date = models.DateTimeField(auto_now=True)

    class Meta:
        ordering = ['-created_date']

    def __str__(self):
        return self.name

blog/forms.py
from django import forms
from captcha.fields import CaptchaField
from blog.models import Comment

class CommentForm(forms.ModelForm):
    # captcha = CaptchaField()
    class Meta:
        model = Comment
        exclude = ('approved',)

blog/views.py
from django.shortcuts import render, redirect, get_object_or_404
from datetime import datetime
from django.utils import timezone
from django.core.paginator import Paginator, EmptyPage, PageNotAnInteger
from .models import Post, PostImage, Comment
from .forms import CommentForm
from django.contrib import messages
from django.db.models import Q

def dark_light_switch(request):
    if 'dark' in request.path:
        return ('dark')
    return ('light')

def check_published_date():
    # Now time with timezone
    now = datetime.now()
    now = timezone.make_aware(datetime(now.year, now.month, now.day, now.hour, now.minute, now.second))
    # Now time without timezone
    # now = datetime(now.year, now.month, now.day, now.hour, now.minute, now.second)
    posts = Post.objects.filter(published_date__lte=now, status=1)
    return posts

# Create your views here.
def index_view(request, **kwargs):
    posts = check_published_date()
    # Category validation ***********************************************************************************
    if kwargs is not None:
        if kwargs.get('cat_name') is not None:
            posts = posts.filter(category__name=kwargs['cat_name'])
        elif kwargs.get('author_username') is not None:
            posts = posts.filter(author__username=kwargs['author_username'])
        elif kwargs.get('tag_name') is not None:
            posts = posts.filter(tag__name=kwargs['tag_name'])
    # Category validation ***********************************************************************************
            
    # Search validations *************************************************************************************
    if request.method == 'GET':
        if x:= request.GET.get('sBar'):
            posts = posts.filter(Q(content_1__contains=x) | Q(content_2__contains=x))
    # Search validations *************************************************************************************
            
    # Deleting duplicated values from tag and category ********************************************************************
    tag_con = []
    cat_con = []
    for post in posts:
        for tag in post.tag.all():
            tag_con.append(str(tag))
        for cat in post.category.all():
            cat_con.append(str(cat))
    tag_con = list(dict.fromkeys(tag_con))
    cat_con = list(dict.fromkeys(cat_con))
    # Deleting duplicated values from tag and category ********************************************************************

    # Pagination *********************************************************************************************
    posts = Paginator(posts, 3)
    try:
        page_number = request.GET.get('page')
        posts = posts.get_page(page_number)
    except EmptyPage:
        posts = posts.get_page(1)
    except PageNotAnInteger:
        posts = posts.get_page(1)
    # Pagination *********************************************************************************************

    context = {'context': posts, 'tag_con': tag_con, 'cat_con': cat_con}
    return render(request, 'blog/light/blog.html', context)

def blog_single_view(request, pid):
    # ******************************** About CommentForm ********************************
    if request.method == 'POST':
        form = CommentForm(request.POST)
        if form.is_valid():
            messages.add_message(request, messages.SUCCESS, 'دیدگاه شما با موفقیت ثبت گردید')
            form.save()
        else:
            messages.add_message(request, messages.ERROR, 'متاسفانه دیدگاه شما ثبت نشد')
    form = CommentForm()
    # ******************************** About CommentForm ********************************

    posts = check_published_date()
    context = get_object_or_404(posts, pk=pid)
    if context.login_require == True and not request.user.is_authenticated:
        messages.add_message(request, messages.INFO, 'You are not logged in<br>Please login')
        # return redirect('accounts:login', 'blog:index')
        return redirect(f"/accounts/{dark_light_switch(request)}/login/?next=" + request.path)
    comments = Comment.objects.filter(post=context.id, approved = True)
    context.counted_views = context.counted_views + 1
    context.save()
    # Finding the post before and after
    nextPost = posts.filter(pk__gt=pid).first()
    prevPost = posts.filter(pk__lt=pid).last()
    images = PostImage.objects.filter(post_id=pid)
    context = {'context': context, 'prevPost': prevPost, 'nextPost': nextPost, 'comments': comments, 'form': form, 'images': images}
    # context = {'context': context, 'prevPost': prevPost, 'nextPost': nextPost, 'images': images}
    # return render(request, 'blog/blog-single.html', context)
    return render(request, 'blog/light/blog-single.html', context)

templates/blog/light/blog-single.html
{% extends 'base.html' %}
{% load static %}
{% load humanize %}
{% load jalali_tags %}
{% block extrahead %}

{% endblock %}
{% load blog_tags %}
{% block content %}
  <!-- wrapper -->
  <div id="wrapper">
    <!-- content-holder -->
    <div class="content-holder">
      <!-- column-image -->
      <div class="column-image">
        <div class="bg" data-bg="{% static 'images/single-post-image.jpg' %}"></div>
        <div class="overlay"></div>
        <div class="column-title">
          <h2>{{context.title}}</h2>
          <h3>{{context.sub_title}}</h3>
        </div>
        <div class="ci_dec">
          <span></span>
        </div>
      </div>
      <!-- column-image end -->
      <!-- column-wrapper -->
      <div class="column-wrapper">
        <!-- section -->
        <section>
          <div class="container small-container">
            <div class="blog-opt">
              {% include 'blog/blog-search.html' %}

              <!-- filter category -->
              <div class="category-filter blog-btn-filter">
                <div class="blog-btn">تگ ها / دسته بندی ها</div>
                <div class="blog-filter-wrap">
                  <div class="blog-filter-wrap_item" data-bfgt="Categories">
                    <ul>
                      {% for cat in context.category.all %}
                        <li>
                          <a href="{% if 'dark' in request.path %}
                              {% url 'blog:category_dark' cat %}
                            {% else %}
                              {% url 'blog:category_light' cat %}
                            {% endif %}">
                            {{ cat }}
                          </a>
                        </li>
                      {% endfor %}
                    </ul>
                  </div>
                  <div class="blog-filter-wrap_item" data-bfgt="Tags">
                    <ul>
                      {% for tag in context.tag.all %}
                        <li>
                          <a href="{% if 'dark' in request.path %}
                              {% url 'blog:tag_dark' tag %}
                            {% else %}
                              {% url 'blog:tag_light' tag %}
                            {% endif %}">
                            {{ tag }}
                          </a>
                        </li>
                      {% endfor %}
                    </ul>
                  </div>
                  <div class="blog-filter-wrap_title"></div>
                </div>
              </div>
              <!-- filter category end -->
            </div>
            <div class="section-title n_dec" style="text-align: right;">
              <h3>{{ context.title }}</h3>
              <h4>{{ context.sub_title }}</h4>
            </div>
            <!-- blog media -->
            <div class="blog-media">
              <div class="single-slider-wrap">
                <div class="single-slider">
                  <div class="swiper-container">
                    <div class="swiper-wrapper lightgallery">
                      <div class="swiper-slide hov_zoom">
                        <img src="{{ context.image_main.url }}" alt="" /><a href="{{ context.image_main.url }}" class="box-media-zoom popup-image"><i class="fal fa-search"></i></a>
                      </div>
                      {% for image in images %}
                        <div class="swiper-slide hov_zoom">
                          <img src="{{ image }}" alt="" /><a href="{{ image }}" class="box-media-zoom popup-image"><i class="fal fa-search"></i></a>
                        </div>
                      {% endfor %}
                    </div>
                  </div>
                </div>
                <div class="single_slider_btn hsc-next">
                  <i class="fal fa-angle-right"></i>
                </div>
                <div class="single_slider_btn hsc-prev">
                  <i class="fal fa-angle-left"></i>
                </div>
              </div>
              <div class="ss-slider-pagination_wrap">
                <div class="ss-slider-pagination"></div>
              </div>
            </div>
            <!-- blog media end -->
            <!-- single-post-container -->
            <div class="single-post-container">
              <p>{{ context.content_1|safe }}</p>
              <div class="post-img-row">
                <div class="post-img-row_item">
                  <img src="{{ context.image_content_1.url }}" class="respimg" alt="" />
                </div>
                <div class="post-img-row_item">
                  <img src="{{ context.image_content_2.url }}" class="respimg" alt="" />
                </div>
              </div>
              <p>{{ context.content_2|safe }}</p>
              {% comment %} <p>Lolibero. Aliquam erats nec. Integer mi, dapibus a ante non, accumsan luctus augue.</p>
              <p>Lorem ipsum ellis quam. Cras nisl mi, dapibus a ante non, accumsan luctus augue.</p>
              <blockquote>
                <p>elit. Cras la inia magna vel molestie faucibus.</p>
              </blockquote>
              <p>Lorem ipsum dolor sit amet, consectetur adipiscing .</p> {% endcomment %}
              <div class="post_opt-wrap">
                <div class="pr-tags">
                  <span>تگ ها :</span>
                  <ul>
                    {% for tag in context.tag.all %}
                      <li>
                        <a href="{% if 'dark' in request.path %}
                            {% url 'blog:tag_dark' tag %}
                          {% else %}
                            {% url 'blog:tag_light' tag %}
                          {% endif %}">
                          {{ tag }}
                        </a>
                      </li>
                    {% endfor %}
                  </ul>
                </div>
                <div class="post-opt_single gray-bg">
                  <span style="{% if 'light' in request.path %}color:black;{% endif %}"><i class="fal fa-eye"></i> {{ context.counted_views }} دیده شده</span>
                </div>
              </div>
              {% include "blog/blog-next-prev.html" %}
            </div>
            <!-- single-post-container end -->
          </div>
        </section>
        <!-- section end -->
        <!-- section -->
        <section>
          <div class="container small-container">
            <div class="section-title n_dec st_small">
              <h3>دیدگاه ها</h3>
            </div>
            <div class="commnets-list">
              <!-- comment-item -->
              {% if comments %}
                {% for comment in comments %}
                  <div class="comment-item">
                    <div class="comment-author">
                      <img alt="" src="{% static 'images/avatar/2.jpg' %}" width="50" height="50" />
                      <h5><a>{{comment.name}}</a></h5>
                      <h6><a>{{comment.created_date|naturaltime}}</a></h6>
                    </div>
                    <div class="comment-body gray-bg">
                      <p>{{comment.message|truncatewords_html:10}}</p>
                      <div class="comm-num">{{forloop.counter}} .</div>
                    </div>
                  </div>
                {% endfor %}
              {% else %}
                <div class="comment-item">
                  <div class="comment-author">
                  </div>
                  <div class="comment-body gray-bg">
                  </div>
                </div>
              {% endif %}
              <!-- comment-item end -->
            </div>
            <div class="comment-form">
              <div class="section-title n_dec st_small">
                <h3>ارسال دیدگاه</h3>
              </div>
              <form class="custom-form" method="post">
                {% csrf_token %}
                <fieldset>
                  <input type="hidden" name="post" value="{{context.id}}">
                  <input type="text" {% if request.user.is_authenticated %}hidden="True" value="{{request.user.first_name}}"{% else %}value=""{% endif %} name="name" id="name" placeholder="* نام" required/>
                  <input type="text" {% if request.user.is_authenticated %}hidden="True" value="{{request.user.email}}"{% else %}value=""{% endif %} name="email" id="email-comment" placeholder="* ایمیل آدرس" style="" required/>
                  <input type="text" name="subject" id="subject" placeholder=":عنوان" value="" required/>
                  <textarea name="message" id="comments" cols="40" rows="3" placeholder=":پیام شما" required></textarea>
                  <button class="btn" id="submit">ارسال</button>
                </fieldset>
              </form>
            </div>
          </div>
        </section>
        <!-- section end -->
        <div class="order-wrap">
          <div class="container small-container">
            <h4>آماده شرکت در گالری هستید؟</h4>
          </div>
          <a href="{% if 'dark' in request.path %}
              {% url 'light_mode:contact_dark' %}
            {% else %}
              {% url 'light_mode:contact' %}
            {% endif %}"
            class="order_btn">
            ارتباط با ما
          </a>
        </div>
      </div>
      <!-- column-wrapper -->
      <!-- fixed-bottom-container -->
      <div class="fixed-bottom-container">
        <div class="scroll-down-wrap">
          <div class="mousey">
            <div class="scroller"></div>
          </div>
        </div>
        <a href="{% url 'light_mode:index_carousel2' %}" class="bth_btn hbn_vis"><i class="fal fa-home-lg-alt"></i><strong>خانه</strong></a>
        <div class="progress-bar-wrap">
          <div class="progress-bar color-bg"></div>
        </div>
      </div>
      <!-- fixed-bottom-container end -->
    </div>
    <!-- content-holder end -->
  </div>
  <!-- wrapper end -->
{% endblock %}

templates/blog/light/blog.html
{% extends 'base.html' %}
{% load static %}
{% load jalali_tags %}
{% block extrahead %}
{% endblock %}
{% load blog_tags %}
{% block content %}
  <!-- wrapper -->
  <div id="wrapper">
    <!-- content-holder -->
    <div class="content-holder">
      <!-- column-image -->
      <div class="column-image">
        <div class="bg" data-bg="{% static 'images/bg/4.jpg' %}"></div>
        <div class="overlay"></div>
        <div class="column-title">
          <h2>تارنگار</h2>
          <h3>!!!در تشخیص قدمت آثار باستانی با ما به روز بمانید</h3>
        </div>
        <div class="ci_dec">
          <span></span>
        </div>
      </div>
      <!-- column-image end -->
      <!-- column-wrapper -->
      <div class="column-wrapper">
        <!-- section -->
        <section id="sec1">
          <div class="container small-container">
            <div class="blog-opt">
              {% include 'blog/blog-search.html' %}

              <!-- filter category -->
              <div class="category-filter blog-btn-filter">
                <div class="blog-btn">تگ ها - دسته بندی ها</div>
                <div class="blog-filter-wrap">
                  <div class="blog-filter-wrap_item" data-bfgt="Categories">
                    <ul>
                      {% for cat in cat_con %}
                        <li>
                          <a href="{% if 'dark' in request.path %}
                              {% url 'blog:category_dark' cat %}
                            {% else %}
                              {% url 'blog:category_light' cat %}
                            {% endif %}">
                            {{ cat }}
                          </a>
                        </li>
                      {% endfor %}
                    </ul>
                  </div>
                  <div class="blog-filter-wrap_item" data-bfgt="Tags">
                    <ul>
                      {% for tag in tag_con %}
                        <li>
                          <a href="{% if 'dark' in request.path %}
                              {% url 'blog:tag_dark' tag %}
                            {% else %}
                              {% url 'blog:tag_light' tag %}
                            {% endif %}">
                            {{ tag }}
                          </a>
                        </li>
                      {% endfor %}
                    </ul>
                  </div>
                  <div class="blog-filter-wrap_title"></div>
                </div>
              </div>
              <!-- filter category end -->
            </div>
            <div class="post-items">
              {% for post in context %}
                <!-- post-item -->
                <div class="post-item">
                  <div class="post-item_wrap">
                    <div class="post-item_media">
                      <a href="{% if 'light' in request.path %}
                          {% url 'blog:blog_single_light' post.id %}
                        {% else %}
                          {% url 'blog:blog_single_dark' post.id %}
                        {% endif %}">
                        <img src="{{ post.image_main.url }}" alt="" />
                      </a>
                    </div>
                    <div class="post-item_content">
                      <div class="post-header">
                        <a href="{% if 'dark' in request.path %}{% url 'blog:category_dark' post.category.first %}{% else %}{% url 'blog:category_light' post.category.first %}{% endif %}">{{ post.category.first }}</a><a>{{ post.published_date|to_jalali:'%H:%M:%S _ %Y/%m/%d' }}</a>
                      </div>
                      <h3>
                        <a href="{% if 'light' in request.path %}
                            {% url 'blog:blog_single_light' post.id %}
                          {% else %}
                            {% url 'blog:blog_single_dark' post.id %}
                          {% endif %}">
                          {{ post.title }}
                        </a>
                      </h3>
                      <p>{{ post.content|safe|truncatewords_html:15 }}</p>
                      <a href="{% if 'light' in request.path %}
                          {% url 'blog:blog_single_light' post.id %}
                        {% else %}
                          {% url 'blog:blog_single_dark' post.id %}
                        {% endif %}"
                        class="single-btn">
                        <span>مشاهده</span>
                      </a>
                    </div>
                  </div>
                </div>
                <!-- post-item end -->
              {% endfor %}
            </div>
            <!-- pagination -->
            {% if context.paginator.count > 0 %}
              <div class="pagination">
                <div class="pr-bg pr-bg-white"></div>
                {% if context.has_previous %}
                  <a href="?page={{ context.previous_page_number }}" class="prevposts-link"><i class="fal fa-long-arrow-left"></i></a>
                {% endif %}
                {% for page in context.paginator.page_range %}
                  <a href="?page={{ page }}" class="{% if context.number == page %}current-page{% endif %}">{{ page }}</a>
                {% endfor %}
                {% comment %} <a href="#" class="current-page">02</a> {% endcomment %}
                {% if context.has_next %}
                  <a href="?page={{ context.next_page_number }}" class="nextposts-link"><i class="fal fa-long-arrow-right"></i></a>
                {% endif %}
              </div>
            {% else %}
              <div class="pagination">
                <div class="pr-bg pr-bg-white"></div>
                <a href="{% if 'light' in request.path %}
                    {% url 'blog:index_light' %}
                  {% else %}
                    {% url 'blog:index_dark' %}
                  {% endif %}"
                  class="current-page">
                  تمامی بلاگ ها
                </a>
              </div>
            {% endif %}
            <!-- pagination end -->
          </div>
        </section>
        <!-- section end -->
        <div class="order-wrap">
          <div class="container small-container">
            <h4>آماده شرکت در گالری هستید؟</h4>
          </div>
          <a href="{% if 'dark' in request.path %}
              {% url 'light_mode:contact_dark' %}
            {% else %}
              {% url 'light_mode:contact' %}
            {% endif %}"
            class="order_btn">
            ارتباط با ما
          </a>
        </div>
      </div>
      <!-- column-wrapper -->
      <!-- fixed-bottom-container -->
      <div class="fixed-bottom-container">
        <div class="scroll-down-wrap">
          <div class="mousey">
            <div class="scroller"></div>
          </div>
        </div>
        <a href="{% url 'light_mode:index_carousel2' %}" class="bth_btn hbn_vis"><i class="fal fa-home-lg-alt"></i><strong>بازگشت به صفحه ی اصلی</strong></a>
        <div class="progress-bar-wrap">
          <div class="progress-bar color-bg"></div>
        </div>
      </div>
      <!-- fixed-bottom-container end -->
    </div>
    <!-- content-holder end -->
  </div>
  <!-- wrapper end -->
{% endblock %}