accounts/urls.py
from django.urls import path
from . import views
# from blog.feeds import LatestEntriesFeed
from django.contrib.auth import views as auth_views

app_name = 'accounts'

urlpatterns = [
    # Login
    path('light/login/', views.login_view, name='login_light'),
    path('dark/login/', views.login_view, name='login_dark'),

    # Logout
    path('light/logout/', views.logout_view, name='logout_light'),
    path('dark/logout/', views.logout_view, name='logout_dark'),

    # Register
    path('light/signup/', views.register_view, name='signup_light'),
    path('dark/signup/', views.register_view, name='signup_dark'),
    
    # Password change
    path('light/change_password/', views.change_password_view, name='change_password_light'),
    path('dark/change_password/', views.change_password_view, name='change_password_dark'),

    path('password_reset/', auth_views.PasswordResetView.as_view(template_name='accounts/password_reset.html'), name='password_reset_light'),
    path('password_reset/', auth_views.PasswordResetView.as_view(template_name='accounts/password_reset.html'), name='password_reset'),
    path('password_reset_done/', auth_views.PasswordResetDoneView.as_view(template_name='accounts/password_reset_done.html'), name='password_reset_done'),
    path('password_reset_confirm/<uidb64>/<token>/', auth_views.PasswordResetConfirmView.as_view(template_name='accounts/password_reset_confirm.html'), name='password_reset_confirm'),
    path('password_reset_complete/', auth_views.PasswordResetCompleteView.as_view(template_name='accounts/password_reset_complete.html'), name='password_reset_complete'),

    # path('password_reset/', auth_views.PasswordResetView.as_view(template_name='password_reset_form.html'), name='password_reset'),
    # path('password_reset_done/', auth_views.PasswordResetDoneView.as_view(template_name='password_reset_done.html'), name='password_reset_done'),
    # path('password_reset_confirm/uidb64/token/',auth_views.PasswordResetConfirmView.as_view(template_name='password_reset_confirm.html'), name='password_reset_confirm'),
    # path('password_reset_complete/', auth_views.PasswordResetCompleteView.as_view(template_name='password_reset_complete.html'), name='password_reset_complete'),
]
    

beyhagh_bastan/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static
from django.contrib.sitemaps.views import sitemap
from light_mode.sitemaps import StaticViewSitemap
from blog.sitemaps import BlogSitemap_single_post, BlogSitemap_category, BlogSitemap_tag
from portfolio.sitemaps import PortfolioSitemap_portfolio, PortfolioSitemap_category, PortfolioSitemap_tag

sitemaps = {
    # It seems that the app name is not important.
    "static": StaticViewSitemap,
    
    # Blog
    "blog_single_post": BlogSitemap_single_post,
    "blog_category": BlogSitemap_category,
    "blog_tag": BlogSitemap_tag,
    
    # Portfolio
    "portfolio_portfolio": PortfolioSitemap_portfolio,
    "portfolio_category": PortfolioSitemap_category,
    "portfolio_tag": PortfolioSitemap_tag,
}

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('main.urls')),
    path('', include('light_mode.urls')),
    path('blog/', include('blog.urls')),
    path('captcha/', include('captcha.urls')),
    path('summernote/', include('django_summernote.urls')),
    path('accounts/', include('accounts.urls')),
    path('portfolio/', include('portfolio.urls')),
    path(
    "sitemap.xml",
    sitemap,
    {"sitemaps": sitemaps},
    name="django.contrib.sitemaps.views.sitemap",),
    path('robots.txt', include('robots.urls')),
]
urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

blog/urls.py
from django.urls import path
from . import views
from blog.feeds import LatestEntriesFeed


app_name = 'blog'

urlpatterns = [
    path('light/', views.index_view, name='index_light'),
    path('dark/', views.index_view, name='index_dark'),
    path('light/blog-<int:pid>/', views.blog_single_view, name='blog_single_light'),
    path('dark/blog-<int:pid>/', views.blog_single_view, name='blog_single_dark'),
    path('dark/category-<str:cat_name>', views.index_view, name='category_dark'),
    path('light/category-<str:cat_name>', views.index_view, name='category_light'),
    path('dark/tag-<str:tag_name>', views.index_view, name='tag_dark'),
    path('light/tag-<str:tag_name>', views.index_view, name='tag_light'),
    path('light/search/', views.index_view, name='search_light'),
    path('dark/search/', views.index_view, name='search_dark'),
    path("light/rss/feed/", LatestEntriesFeed()),
    # path('light/search/', views.index_view, name='search_light'),
]

light_mode/urls.py
from django.urls import path
from . import views

app_name = 'light_mode'

# It is useable when that moved on db
# Debug is False
# from django.conf.urls import handler404
# handler404 = 'light_mode.views.custom_404'

urlpatterns = [
    # ********************************************* Home pages ****************************************
    path('light/', views.index_carousel2_view, name='index_carousel2'),
    path('dark/', views.index_carousel2_view, name='index_carousel2_dark'),
    # path('', views.index_slider_view, name='index_slider'),
    # path('', views.index_carousel_view, name='index_carousel'),
    # path('', views.index_video_view, name='index_video'),
    # path('', views.index_imagesGrid_view, name='index_imagesGrid'),
    # ********************************************* Home pages ****************************************

    path('light/404_error_page/', views.error_page_404, name='404_error_page'),

    path('light/about/', views.about_view, name='about'),
    path('dark/about/', views.about_view, name='about_dark'),
    path('light/contact/', views.contact_view, name='contact'),
    path('dark/contact/', views.contact_view, name='contact_dark'),
    path('newsletter', views.newsletter_view, name='news_letter'),
]

main/urls.py
from django.urls import path
from . import views

app_name = 'main'

urlpatterns = [
    # path('', views.comming_soon_view, name='coming_soon_index'),
    path('', views.index_view, name='index'),
]

portfolio/urls.py
from django.urls import path
from . import views
# from blog.feeds import LatestEntriesFeed
from django.contrib.auth import views as auth_views
from portfolio.feeds import LatestEntriesFeed


app_name = 'portfolio'

urlpatterns = [
    path('light/', views.index_view, name='portfolio_light'),
    path('dark/', views.index_view, name='portfolio_dark'),
    path('light/category-<str:cat_name>', views.index_view, name='category_light'),
    path('dark/category-<str:cat_name>', views.index_view, name='category_dark'),
    path('light/tag-<str:tag_name>', views.index_view, name='tag_light'),
    path('dark/tag-<str:tag_name>', views.index_view, name='tag_dark'),
    path('search/', views.index_view, name='search'),
    path('light/single-<int:pid>', views.portfolio_single_view, name='portfolio_single_light'),
    path('dark/single-<int:pid>', views.portfolio_single_view, name='portfolio_single_dark'),
    path("light/rss/feed/", LatestEntriesFeed()),

]
    

templates/base.html
{% load static %}
{% load humanize %}
{% load jalali_tags %}
{% load blog_tags %}
{% comment %} {% load compress %} {% endcomment %}
<!DOCTYPE HTML>
<html lang="en">
  <head>
    <!-- =============== basic =============== -->
    <meta charset="UTF-8" />
    <meta http-equiv="x-ua-compatible" content="ie=edge" />
    <title>Mr.BoO - Beyhagh-bastan</title>
    <!-- =============== css =============== -->
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css" />
    {% comment %} {% compress css %} {% endcomment %}
    <link rel="stylesheet" href="{% static 'admin/jquery.ui.datepicker.jalali/themes/base/jquery-ui.min.css' %}" />
    <link type="text/css" rel="stylesheet" href="{% static 'css/plugins.css' %}" />
    <link type="text/css" rel="stylesheet" href="{% static 'css/style.css' %}" />
    <link type="text/css" rel="stylesheet" href="{% static 'css/map.css' %}" />
    {% if 'light' in request.path %}
      <link type="text/css" rel="stylesheet" href="{% static 'css/light-style.css' %}" />
    {% endif %}
    {% comment %} {% endcompress %} {% endcomment %}

    {% comment %} ********************* Light Gallery ********************* {% endcomment %}
    <link href="https://cdn.jsdelivr.net/lightgallery/1.3.9/css/lightgallery.min.css" rel="stylesheet">
    <link href="https://cdn.jsdelivr.net/lightgallery/1.3.9/css/transistions.min.css" rel="stylesheet">
    {% comment %} ********************* Light Gallery ********************* {% endcomment %}

    {% block extrahead %}

    {% endblock %}
    <!-- =============== favicons =============== -->
    <link rel="shortcut icon" href="{% static 'images/favicon.ico' %}" />
  </head>
  <body>
    <!-- main start -->
    <div id="main">
      <!-- loader -->
      <div class="main-loader">
        <div class="ml-wrap" style="display: inline;">
          <div class="ml-mask"></div>
          <img src="{% if 'light' in request.path %}
              {% static 'images/beyhagh-bastan-black(text).png' %}
            {% else %}
              {% static 'images/beyhagh-bastan-white(text).png' %}
            {% endif %}"
            alt="" />
        </div>
        <div class="ml_images-wrap">
          <div class="ml_bg-item" style="top:-30px; left: 0">
            <div class="bg" data-bg="{% static 'images/folio/2.jpg' %}"></div>
          </div>
          <div class="ml_bg-item" style="bottom:  -20px; left: 50px">
            <div class="bg" data-bg="{% static 'images/folio/6.jpg' %}"></div>
          </div>
          <div class="ml_bg-item" style="top:30px; right: -120px">
            <div class="bg" data-bg="{% static 'images/folio/18.jpg' %}"></div>
          </div>
        </div>
      </div>
      <!-- loader end -->
      <!-- header main-header -->
      <header class="main-header">
        <div class="main-inner">
          <!-- logo -->
          <a href="{% url 'main:index' %}" class="logo-holder">
            <img src="{% if 'light' in request.path %}
                {% static 'images/beyhagh-bastan-black.png' %}
              {% else %}
                {% static 'images/beyhagh-bastan-white.png' %}
              {% endif %}"
              alt="" />
          </a>
          <!-- logo end -->
          <!-- sb-button -->
          <div class="sb-button c_sb">
            <span></span>
          </div>
          <!-- sb-button end -->
          <!-- mobile nav -->
          <div class="nav-button-wrap">
            <div class="nav-button">
              <span></span><span></span><span></span>
            </div>
          </div>
          <!-- mobile nav end -->
          <!-- share btn -->
          <div class="share-btn">
            {% if request.user.is_authenticated %}
              <span class="hi_user">{{request.user.username}} درود بر</span>
              <span><a {% if 'light' in request.path %}href="{% url 'accounts:change_password_light' %}?next={{request.get_full_path}}"{% else %}href="{% url 'accounts:change_password_dark' %}?next={{request.get_full_path}}" style="color: white;"{% endif %}>تغییر پسورد</a></span>
              <span><a {% if 'light' in request.path %}href="{% url 'accounts:logout_light' %}?next={{request.get_full_path}}" style="color: black;"{% else %}href="{% url 'accounts:logout_dark' %}?next={{request.get_full_path}}" style="color: white;"{% endif %}>خروج</a></span>
            {% else %}
            {% comment %} <p>{{request.get_full_path}}</p> {% endcomment %}
              <a {% if 'light' in request.path %}href="{% url 'accounts:login_light' %}?next={{request.get_full_path}}" style="color: black;"{% else %}href="{% url 'accounts:login_dark' %}?next={{request.get_full_path}}" style="color: white;"{% endif %}><span>ورود / ثبت نام</span></a>
            {% endif %}
          </div>
          <!-- share btn end -->
          <!-- navigation -->
          <div class="nav-holder main-menu">
            <nav>
              <ul>
                <li>
                  <a href="{% if 'light' in request.path %}
                      {% url 'light_mode:contact' %}
                    {% else %}
                      {% url 'light_mode:contact_dark' %}
                    {% endif %}"
                    class="{% if 'contact' in request.path %}act-link{% endif %}">
                    ارتباط با ما
                  </a>
                </li>
                <li>
                  <a href="{% if 'light' in request.path %}
                      {% url 'light_mode:about' %}
                    {% else %}
                      {% url 'light_mode:about_dark' %}
                    {% endif %}"
                    class="{% if 'about' in request.path %}act-link{% endif %}">
                    در باره ی ما
                  </a>
                </li>
                <li>
                  <a href="{% if 'light' in request.path %}
                      {% url 'blog:index_light' %}
                    {% else %}
                      {% url 'blog:index_dark' %}
                    {% endif %}"
                    class="{% if 'blog' in request.path %}act-link{% endif %}">
                    بلاگ
                  </a>
                </li>
                <li>
                  <a href="{% if 'dark' in request.path %}{% url 'portfolio:portfolio_dark' %}{% else %}{% url 'portfolio:portfolio_light' %}{% endif %}" class="{% if 'portfolio' in request.path %}act-link{% endif %}">محصولات</a>
                </li>
                <li>
                  <a href="{% if 'light' in request.path %}
                      {% url 'light_mode:index_carousel2' %}
                    {% else %}
                      {% url 'light_mode:index_carousel2_dark' %}
                    {% endif %}"
                    class="{% if '/light/' == request.path or '/dark/' == request.path %}act-link{% endif %}">
                    خانه
                  </a>
                </li>
              </ul>
            </nav>
          </div>
        </div>
      </header>
      <!-- Header end -->
      {% block content %}

      {% endblock %}
      <!-- aside-column -->

      {% include 'social_links.html' %}

      <!-- aside-column end -->
      <!-- footer -->
      <footer class="main-footer">
        <div class="footer_contacts">
          <ul>
            <li>
              <span>Mail :</span><a target="_blank">beyhagh.bastan.antique@gmail.com</a>
            </li>
            <li>
              <span>Phone :</span><a>09155710393 - 09305717572</a>
            </li>
          </ul>
        </div>
        <div class="policy-box">Mr.BoO 2023 . All rights reserved.</div>
      </footer>
      <div class="to-top-btn to-top">
        <i class="fal fa-long-arrow-up"></i>
      </div>
      <!-- footer end -->
      <div class="aside_dec"></div>
      <!-- sidebar -->
      <div class="sidebar-wrap">
        <div class="sidebar-wrap-container">
          {% latest_posts 4 %}

          <!-- sb-widget-wrap -->
          
          {% include "news-letter.html" %}

          <!-- sb-widget-wrap end -->
          <!-- sb-widget-wrap -->
          <div class="sb-widget-wrap fl-wrap">
            <h3>Social Links</h3>
            <div class="sb-widget fl-wrap">
              <div class="sidebar-social fl-wrap">
                <ul>
                  <li>
                    <a href="#" target="_blank">Fb</a>
                  </li>
                  <li>
                    <a href="#" target="_blank">Tw</a>
                  </li>
                  <li>
                    <a href="#" target="_blank">Ins</a>
                  </li>
                  <li>
                    <a href="#" target="_blank">Tic</a>
                  </li>
                </ul>
              </div>
            </div>
          </div>
          <!-- sb-widget-wrap end -->
        </div>
      </div>
      <div class="sb-overlay"></div>
      <!-- sidebar end -->
    </div>
    <!-- Main end -->
    <!-- =============== scripts =============== -->
    {% comment %} {% compress js %} {% endcomment %}
    <script src="https://cdn.jsdelivr.net/npm/sweetalert2@11.4.8/dist/sweetalert2.all.min.js"></script>
    <script src="{% static 'admin/js/django_jalali.min.js' %}"></script>
    <script src="{% static 'js/jquery.min.js' %}"></script>
    <script src="{% static 'js/plugins.js' %}"></script>
    <script src="{% static 'js/scripts.js' %}"></script>
    <script src="{% static 'js/map.js' %}"></script>

    {% comment %} ********************* Light Gallery for useing mousewheel in gallery show ********************* {% endcomment %}
    <script src="https://cdnjs.cloudflare.com/ajax/libs/jquery-mousewheel/3.1.13/jquery.mousewheel.min.js"></script>
    {% comment %} ********************* Light Gallery for useing mousewheel in gallery show ********************* {% endcomment %}
    {% comment %} {% endcompress %} {% endcomment %}
  </body>
  <!-- Main msg for all pages *********************************************************************************** -->
  {% comment %} {% if messages %}
    {% for message in messages %}
      {% if message.tags == 'alert-success' %}
        <script>
          Swal.fire({
            icon: 'success',
            title: 'Well',
            html: '{{message|safe}}',
            footer: '<a href="/">Home</a>'
          })
        </script>
      {% elif message.tags == 'alert-error' %}
        <script>
          Swal.fire({
            icon: 'error',
            title: 'Oops...',
            html: '{{message|safe}}',
            footer: '<a href="/">Home</a>'
          })
        </script>
      {% endif %}
    {% endfor %}
  {% endif %} {% endcomment %}
{% if messages %}
  {% for message in messages %}
    <p>{{ message|safe }}</p>
    {% if message.tags == 'alert-success' %}
      <script>
        Swal.fire({
          icon: 'success',
          title: 'Well...',
          html: '{{message|safe}}',
          footer: '<a href="/">Home</a>'
        })
      </script>
    {% elif message.tags == 'alert-danger' %}
      <script>
        Swal.fire({
          icon: 'error',
          title: 'Oops...',
          html: '{{message|safe}}',
          footer: '<a href="/">Home</a>'
        })
      </script>
    {% elif message.tags == 'alert-info' %}
      <script>
        Swal.fire({
          icon: 'info',
          title: 'Attention...',
          html: '{{message|safe}}',
          footer: '<a href="/">Home</a>'
        })
      </script>
    {% endif %}
  {% endfor %}
{% endif %}
  <!-- Main msg for all pages *********************************************************************************** -->
</html>

templates/news-letter.html
{% load static %}
<!-- sb-widget-wrap -->
<div class="sb-widget-wrap fl-wrap">
  <h3>برای دریافت اخبار مارا دنبال کنید</h3>
  <div class="sb-widget fl-wrap">
    <p>سریع ترین راه برای اشتراک اخبار سایت با شما دوست عزیز</p>
    <div class="subcribe-form fl-wrap">
      <form action="{% url 'light_mode:news_letter' %}" id="subscribe" method="post">
            {% csrf_token %}
            <input type="hidden" value="{{ request.get_full_path }}" name="path" />
            <input class="enteremail" name="email" id="subscribe-email" placeholder="آدرس ایمیل" spellcheck="false" type="email" required />
            <button type="submit" id="subscribe-button" class="subscribe-button">ثبت</button>
            <label for="subscribe-email" class="subscribe-message"></label>
      </form>
    </div>
  </div>
</div>
<!-- sb-widget-wrap end -->

templates/social_links.html
{% load static %}
<div class="aside-column">
    <!-- social_links-->
    <div class="header_social">
        <ul>
            <li><a target="_blank">Fb</a></li>
            <li><a target="_blank">Ins</a></li>
            <li><a target="_blank">Tw</a></li>
            <li><a target="_blank">Tic</a></li>
        </ul>
    </div>
    <!-- social_links end-->			
</div>